### ISSUE TITLE
Requesting to give a copyright credit with URL linking to my repo

### ISSUE THREAD

**Issue by jhasuraj01** [jhamadhav/point-classification-ml#1]
It Seems as if your [ML Logic](https://github.com/jhamadhav/point-classification-ml/blob/3ca590b8ccc93445075398cac57941b43d60bd85/scripts/main.js#L78) is very much inspired by my [Point Classification AI](https://github.com/jhasuraj01/ai/blob/4e3326eabf76984d6a309e23e98be50bb51bceb2/point-classification/index.js#L50) at [@jhasuraj01/ai/point-classification](https://github.jhasuraj.com/ai/blob/master/point-classification/).

Since I hadn't provided any license you do not have any rights to modify or copy my logic of POINT CLASSIFICATION AI.

Instead, you must give a credit of AI logic to the person/repository you have been inspired by.

Thank You.

**Comment by jhamadhav** [comment]
Bruh what the F 😶

**Comment by jhamadhav** [comment]
The logic used is generic and has been present way before your code..
If any thing my implementation is better suited for the problem

1. In my implementation the line can move in both horizontal and vertical direction.
2. In your implementation you have used the pseudo line to minimize error where as in my code I have calculated the error without any info of the pseudo line meaning it is more suited to be called _learning_.

**Comment by jhasuraj01** [comment]
### Your understanding for my code shows how thoroughly you went through it and copied it!

#### You are mixing the concept of Visualization and Learning
- I used so called **Pseudo line** to create data points **not for the learning** itself
- Moving lines on canvas is visualization and i am not asking for credits for visualization.

> Don't forget I explained you my whole logic on voice call.

I am pointing your code written from [line 78](https://github.com/jhamadhav/point-classification-ml/blob/3ca590b8ccc93445075398cac57941b43d60bd85/scripts/main.js#L78) to [Line 188](https://github.com/jhamadhav/point-classification-ml/blob/3ca590b8ccc93445075398cac57941b43d60bd85/scripts/main.js#L188) which is similar to my code from [line 50](https://github.com/jhasuraj01/ai/blob/4e3326eabf76984d6a309e23e98be50bb51bceb2/point-classification/index.js#L50) to [line 94](https://github.com/jhasuraj01/ai/blob/4e3326eabf76984d6a309e23e98be50bb51bceb2/point-classification/index.js#L94).

**The Logic used in the [trainer function](https://github.com/jhasuraj01/ai/blob/4e3326eabf76984d6a309e23e98be50bb51bceb2/point-classification/index.js#L50) is not generic because it is not the standard method of any machine learning model.**

*You should give the credits for code sample as mentioned and logic for training as mentioned .*

**Comment by jhamadhav** [comment]
Well it's true that you helped me a lot by explaining the logic. So credit where credit is due but saying that I blatantly copied is a disgrace.
